name: Node.js Package

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Show directory contents
        run: ls -l
      - name: Change directory
        run: cd backend
      - name: install dependencies
        run: npm i
      - name: run backend tests
        run: npm run test