name: Node.js Package

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        run: npm i
      - name: run backend
        run: npm run start
      - name: start backend
        run: npm run start &
      - name: run frontend tests
        run: npm run cy:run