name: SonarQube analysis
on:
  push
permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args:
            -Dsonar.projectKey=todo-reihe-links
