name: Tests and SonarQube analysis

on:
  push

jobs:
  defaults:
    run:
    working-directory: ./backend
  backend-tests:
    build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        run: npm i
      - name: run backend tests
        run: npm run test
  frontend-tests:
    build:
      runs-on: ubuntu-latest

      services:
        mongo:
          image: mongo
          ports:
            - 27017:27017
      steps:
        - name: Check out repository
          uses: actions/checkout@v4
        - name: Setup node
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: install dependencies
          run: npm i
        - name: start application
          run: npm run start &
        - name: run tests
          run: npm run cy:run